### ISSUE TITLE
Two Bug

### ISSUE THREAD

**Issue by aokihu** [song940/homekit#1]
First, node-persist as storage is not initialization, I cost many time to debug it 
the second, the cache system is not work well, `this._cache = {}` is not initialization，it show undefined type when running

at the last, the project is not work very well, did you test it before you publish it?

**Comment by lsongdev** [comment]
Thanks for your feedback, This code is still early stage, If you find an issue/problem, fork it and issue a pull request. No matter what, enjoy and do cool things with this code.
